api = "0.2"

[buildpack]
  id = "paketo-buildpacks/php-dist"
  name = "PHP Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    php = "7.2.*"

  [[metadata.dependencies]]
    deprecation_date = "2020-11-30T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "68bcd47857b896b6b9a87d6fc7e0c1079feac48a5d6bedacee4433c023d5f568"
    source = "https://php.net/distributions/php-7.2.28.tar.gz"
    source_sha256 = "ed5fede7602ccd8d1294b4e4aef7f92f4e3af58ab040bd349264b3f5dbef3261"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.28-linux-x64-cflinuxfs3-68bcd478.tgz"
    version = "7.2.28"

  [[metadata.dependencies]]
    deprecation_date = "2020-11-30T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "8e1a95c6308179dae299af027e2cddcb94bac835910fad451641be8590be3038"
    source = "https://php.net/distributions/php-7.2.29.tar.gz"
    source_sha256 = "ea5c96309394a03a38828cc182058be0c09dde1f00f35809622c2d05c50ee890"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.29-linux-x64-cflinuxfs3-8e1a95c6.tgz"
    version = "7.2.29"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-06T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "196175a93983855fbec7b929f6e74b9c8812082f1edf4aad676a507ee3a806d8"
    source = "https://php.net/distributions/php-7.3.15.tar.gz"
    source_sha256 = "c606dd09de2edff1e6b6c5b9f0076214a59f6f1a3272e15d681ed16257737ef6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.15-linux-x64-cflinuxfs3-196175a9.tgz"
    version = "7.3.15"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-06T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "92a3b424233b27d26a8043e108c1a603779de3e791c282a0ef582966ba245fa6"
    source = "https://php.net/distributions/php-7.3.16.tar.gz"
    source_sha256 = "a01ae4f6baf427413c28f8cfddbae86aeff61cdb88658e75404f2d93d98e3255"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.16-linux-x64-cflinuxfs3-92a3b424.tgz"
    version = "7.3.16"

  [[metadata.dependencies]]
    deprecation_date = "2022-11-08T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "787e1173b331249b226464fa1d8ea0ec874af9e26f8fe1ee3a45952e32b07cab"
    source = "https://php.net/distributions/php-7.4.4.tar.gz"
    source_sha256 = "1581b3e10c7854597e1086937d5753cdf92d132865c06a50aed4f4f407138616"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.4-linux-x64-cflinuxfs3-787e1173.tgz"
    version = "7.4.4"

  [[metadata.dependencies]]
    deprecation_date = "2022-11-08T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "c0055c537f9686a1d99344951bedb5286fbf7eee38476b8512516f2b7e8823d3"
    source = "https://php.net/distributions/php-7.4.5.tar.gz"
    source_sha256 = "1ef619411b0bd68c0fbfd2a6c622ad6bc524d0bceb8476fb9807a23a0fe9a343"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7_7.4.5_linux_x64_cflinuxfs3_c0055c53.tgz"
    version = "7.4.5"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-11-30T00:00:00Z
    link = "http://php.net/supported-versions.php"
    match = "7.2.\\d+"
    name = "php"
    version_line = "7.2.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-06T00:00:00Z
    link = "http://php.net/supported-versions.php"
    match = "7.3.\\d+"
    name = "php"
    version_line = "7.3.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-11-08T00:00:00Z
    link = "http://php.net/supported-versions.php"
    match = "7.4.\\d+"
    name = "php"
    version_line = "7.4.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
