
[buildpack]
id = "org.cloudfoundry.buildpacks.php"
name = "PHP Buildpack"
version = "0.0.2"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "f022b5bdb970522d0cce10022a31288571aa167af03fd1e5870cba9cb6afbf19"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.26-linux-x64-cflinuxfs2-f022b5bd.tgz"
version = "7.1.26"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "26f1a5bfd498bce538bf719af852cf79192e222fa91d8a12b6809742df61eeca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.26-linux-x64-cflinuxfs3-26f1a5bf.tgz"
version = "7.1.26"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "b80f91794d4b6eff1a506a700fc23f32d562636ca51cb8fa006f922fba6c199e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.27-linux-x64-cflinuxfs2-b80f9179.tgz"
version = "7.1.27"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "360e142594f4d03d9059ebf576b4d53f1abe43d131f453e3f4fad9bb7d2872f1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.27-linux-x64-cflinuxfs3-360e1425.tgz"
version = "7.1.27"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "e8b205714e7394fcf677ff5df4b51ef24e20a592da4f6067495c173252bd43d0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.15-linux-x64-cflinuxfs2-e8b20571.tgz"
version = "7.2.15"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "73e290036e5a52d45dfa49f66fcaec97c314592699ee240e6a5728dce5ab36ee"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.15-linux-x64-cflinuxfs3-73e29003.tgz"
version = "7.2.15"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "4977ad7e169cc1c8e0d3ed27c0f20e37fbe7869af3e28ca3d88cfb793c9c0baf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.16-linux-x64-cflinuxfs2-4977ad7e.tgz"
version = "7.2.16"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "d5df79808b246afbcb470cd94fab5a90682661fcb745f9edd1c5759f0eeda4f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.16-linux-x64-cflinuxfs3-d5df7980.tgz"
version = "7.2.16"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "9165a32b6e3b604967b822cffa76de7f060758987e9cd3f395cd7f2496c38112"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.2-linux-x64-cflinuxfs3-9165a32b.tgz"
version = "7.3.2"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "57ea9a7d733f720ddfcaa6441c8edb54e6860b399865a654b2897222f2113e79"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.3-linux-x64-cflinuxfs3-57ea9a7d.tgz"
version = "7.3.3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
