api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php-dist"
  name = "PHP Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    php = "7.2.*"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "002f7fd0ab7c13cfe5a2046923ede121b9b29eae3e7feec0d58fdc8aebcbe554"
    source = "https://php.net/distributions/php-7.2.25.tar.gz"
    source_sha256 = "b2cb1bd46454d33b2c65c2fd559f464cd14e57dd47b953adf5caa77fdf0de52b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.25-linux-x64-cflinuxfs3-002f7fd0.tgz"
    version = "7.2.25"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "d7884fb84b32e12e7133108e7de27fa65ead818f908aaafc87fe7f72f106ab78"
    source = "https://php.net/distributions/php-7.2.26.tar.gz"
    source_sha256 = "e97d0636478bb519cd955a0c17b7970cf173063a840a83fc4afb75c22bc1bf08"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.26-linux-x64-cflinuxfs3-d7884fb8.tgz"
    version = "7.2.26"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "ab805a1339e76bc914b12dde4b8472d6dc8fef3d8805e194a47bdb1dd232f96c"
    source = "https://php.net/distributions/php-7.3.12.tar.gz"
    source_sha256 = "d617e5116f8472a628083f448ebe4afdbc4ac013c9a890b08946649dcbe61b34"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.12-linux-x64-cflinuxfs3-ab805a13.tgz"
    version = "7.3.12"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "673ff87b597d893ed2754a158d31f66c4a564fd5bedf1eb600b03b1186c4fbba"
    source = "https://php.net/distributions/php-7.3.13.tar.gz"
    source_sha256 = "9cf835416a3471d7e6615e9288e76813d55ffaf60e0aa9ce74884a7c228cb6dd"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.13-linux-x64-cflinuxfs3-673ff87b.tgz"
    version = "7.3.13"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "9cc811b5af1909ecd1f3f34034bfa242f8a4caabcf9adbb0d22b6f9529a1a228"
    source = "https://php.net/distributions/php-7.4.0.tar.gz"
    source_sha256 = "004a1a8176176ee1b5c112e73d705977507803f425f9e48cb4a84f42b22abf22"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.0-linux-x64-cflinuxfs3-9cc811b5.tgz"
    version = "7.4.0"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "eeb23b618e69ae7a9992ad5a672a5b0f3c34334976f5765b70c630c167bb9120"
    source = "https://php.net/distributions/php-7.4.1.tar.gz"
    source_sha256 = "67265d6bd48d828f4725964f71ca5c76c3da63b0d07bec5ec4e5acfdd3708073"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.1-linux-x64-cflinuxfs3-eeb23b61.tgz"
    version = "7.4.1"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-11-30T00:00:00Z
    link = "http://php.net/supported-versions.php"
    name = "php"
    version_line = "7.2.x"
    match = "7.2.\\d+"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-06T00:00:00Z
    link = "http://php.net/supported-versions.php"
    name = "php"
    version_line = "7.3.x"
    match = "7.3.\\d+"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-11-08T00:00:00Z
    link = "http://php.net/supported-versions.php"
    name = "php"
    version_line = "7.4.x"
    match = "7.4.\\d+"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
