api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php-dist"
  name = "PHP Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    php = "7.2.*"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "b93d98c0d87e1fc5750579b7e3e1c372cccddc0abae60ae15d829694424c4820"
    source = "https://php.net/distributions/php-7.2.26.tar.gz"
    source_sha256 = "e97d0636478bb519cd955a0c17b7970cf173063a840a83fc4afb75c22bc1bf08"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.26-linux-x64-cflinuxfs3-b93d98c0.tgz"
    version = "7.2.26"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "0f759fe1c485634fa5617ce86af5c667d9b79a17b814cc4a546293215a8a1951"
    source = "https://php.net/distributions/php-7.2.27.tar.gz"
    source_sha256 = "e00ace5e89cb162cba0aebd17144541e1c4d965589155a44ca706d9f9c5a8981"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.27-linux-x64-cflinuxfs3-0f759fe1.tgz"
    version = "7.2.27"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "1485c3b3bbdbe2d52acf5e71c88ff25786493eb7c43cb0df131b5c616ba1ca7b"
    source = "https://php.net/distributions/php-7.3.13.tar.gz"
    source_sha256 = "9cf835416a3471d7e6615e9288e76813d55ffaf60e0aa9ce74884a7c228cb6dd"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.13-linux-x64-cflinuxfs3-1485c3b3.tgz"
    version = "7.3.13"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "c3059cdeb6f898cde79ddcc6192340e963ce281c1b6434ce9bbcd8a11313dca9"
    source = "https://php.net/distributions/php-7.3.14.tar.gz"
    source_sha256 = "6aff532a380b0f30c9e295b67dc91d023fee3b0ae14b4771468bf5dda4cbf108"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.14-linux-x64-cflinuxfs3-c3059cde.tgz"
    version = "7.3.14"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "9e9456fd76856919da294fb1db28c0914e6531c3fa50c78739598307b69f7808"
    source = "https://php.net/distributions/php-7.4.1.tar.gz"
    source_sha256 = "67265d6bd48d828f4725964f71ca5c76c3da63b0d07bec5ec4e5acfdd3708073"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.1-linux-x64-cflinuxfs3-9e9456fd.tgz"
    version = "7.4.1"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "1e9c9d46cfc6ff62bd38203ba8e30f9087e3c979d31b6f9bd4fa654dd5ad539a"
    source = "https://php.net/distributions/php-7.4.2.tar.gz"
    source_sha256 = "e1b8dbf561ac1d871362054ff4cd62dca5e19c8c896567996525dda7c4b320f9"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.2-linux-x64-cflinuxfs3-1e9c9d46.tgz"
    version = "7.4.2"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-11-30T00:00:00Z
    link = "http://php.net/supported-versions.php"
    name = "php"
    version_line = "7.2.x"
    match = "7.2.\\d+"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-06T00:00:00Z
    link = "http://php.net/supported-versions.php"
    name = "php"
    version_line = "7.3.x"
    match = "7.3.\\d+"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-11-08T00:00:00Z
    link = "http://php.net/supported-versions.php"
    name = "php"
    version_line = "7.4.x"
    match = "7.4.\\d+"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
