
[buildpack]
id = "org.cloudfoundry.buildpacks.php"
name = "PHP Buildpack"
version = "0.0.2"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "b80f91794d4b6eff1a506a700fc23f32d562636ca51cb8fa006f922fba6c199e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.27-linux-x64-cflinuxfs2-b80f9179.tgz"
version = "7.1.27"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "360e142594f4d03d9059ebf576b4d53f1abe43d131f453e3f4fad9bb7d2872f1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.27-linux-x64-cflinuxfs3-360e1425.tgz"
version = "7.1.27"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "c89b88281097ec3885a6837094d835d8f586853d356bcfd90180515e81c4bb41"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.28-linux-x64-cflinuxfs2-c89b8828.tgz"
version = "7.1.28"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "366b92fb55c057ac2ee805271790382584a387299fcf0ced1e233dd5fe181482"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.28-linux-x64-cflinuxfs3-366b92fb.tgz"
version = "7.1.28"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "4977ad7e169cc1c8e0d3ed27c0f20e37fbe7869af3e28ca3d88cfb793c9c0baf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.16-linux-x64-cflinuxfs2-4977ad7e.tgz"
version = "7.2.16"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "d5df79808b246afbcb470cd94fab5a90682661fcb745f9edd1c5759f0eeda4f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.16-linux-x64-cflinuxfs3-d5df7980.tgz"
version = "7.2.16"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "528d82cdbdf499fcac770e8822db7e8350bd1d050f0c5754ea2466fd0d02b247"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.18-linux-x64-cflinuxfs2-528d82cd.tgz"
version = "7.2.18"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "1e80707ed042c92a8e7df0e263f92e0c7296f200cc04ce2b19916344b1715eaa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.18-linux-x64-cflinuxfs3-1e80707e.tgz"
version = "7.2.18"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "57ea9a7d733f720ddfcaa6441c8edb54e6860b399865a654b2897222f2113e79"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.3-linux-x64-cflinuxfs3-57ea9a7d.tgz"
version = "7.3.3"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "b919dac634ae2b825bf0c1f99cc617ab6de983f22c3b7bc6e07c9c713843ccec"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.5-linux-x64-cflinuxfs3-b919dac6.tgz"
version = "7.3.5"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
