
[buildpack]
id = "org.cloudfoundry.buildpacks.php"
name = "PHP Buildpack"
version = "0.0.1"

[[metadata.dependencies]]
id = "php"
name = "PHP Buildpack"
sha256 = "fe179853efe050a800d1789189dc2fdbf969ae1fb872032da71045b5bf9be777"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.13-linux-x64-cflinuxfs2-fe179853.tgz"
version = "7.2.13"

[[metadata.dependencies]]
id = "php"
name = "PHP Buildpack"
sha256 = "fb2e6e50f30859fd275b92807fffd15eae032d8ad0a2779ce87775b9f30b2611"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.13-linux-x64-cflinuxfs3-fb2e6e50.tgz"
version = "7.2.13"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
