api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php-dist"
  name = "PHP Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    php = "7.2.*"

  [[metadata.dependencies]]
    deprecation_date = "2020-11-30T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "a184353e48ebc16296865a3ed46baf9037211f9bfbc6c746f78a8cacc7cf5f13"
    source = "https://php.net/distributions/php-7.2.27.tar.gz"
    source_sha256 = "e00ace5e89cb162cba0aebd17144541e1c4d965589155a44ca706d9f9c5a8981"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.27-linux-x64-cflinuxfs3-a184353e.tgz"
    version = "7.2.27"

  [[metadata.dependencies]]
    deprecation_date = "2020-11-30T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "68bcd47857b896b6b9a87d6fc7e0c1079feac48a5d6bedacee4433c023d5f568"
    source = "https://php.net/distributions/php-7.2.28.tar.gz"
    source_sha256 = "ed5fede7602ccd8d1294b4e4aef7f92f4e3af58ab040bd349264b3f5dbef3261"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.28-linux-x64-cflinuxfs3-68bcd478.tgz"
    version = "7.2.28"

  [[metadata.dependencies]]
    id = "php"
    name = "PHP"
    sha256 = "1438d01aaa84259cc5f4c5b7f6ec2d26627f7554def47aedc03380d76b4f74ea"
    source = "https://php.net/distributions/php-7.3.13.tar.gz"
    source_sha256 = "9cf835416a3471d7e6615e9288e76813d55ffaf60e0aa9ce74884a7c228cb6dd"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.13-linux-x64-cflinuxfs3-1438d01a.tgz"
    version = "7.3.13"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-06T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "196175a93983855fbec7b929f6e74b9c8812082f1edf4aad676a507ee3a806d8"
    source = "https://php.net/distributions/php-7.3.15.tar.gz"
    source_sha256 = "c606dd09de2edff1e6b6c5b9f0076214a59f6f1a3272e15d681ed16257737ef6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.15-linux-x64-cflinuxfs3-196175a9.tgz"
    version = "7.3.15"

  [[metadata.dependencies]]
    deprecation_date = "2022-11-08T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "8f48263a6f3d011d7337a0ef826b9061194ef89b25f8215e43defec7f0b322ac"
    source = "https://php.net/distributions/php-7.4.2.tar.gz"
    source_sha256 = "e1b8dbf561ac1d871362054ff4cd62dca5e19c8c896567996525dda7c4b320f9"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.2-linux-x64-cflinuxfs3-8f48263a.tgz"
    version = "7.4.2"

  [[metadata.dependencies]]
    deprecation_date = "2022-11-08T00:00:00Z"
    id = "php"
    name = "PHP"
    sha256 = "36aaa3d8022652c4188a2410370ee8f63d04bd347aaaa4a9de8f7092b4aefc45"
    source = "https://php.net/distributions/php-7.4.3.tar.gz"
    source_sha256 = "58e421a1dba10da8542a014535cac77a78f0271afb901cc2bd363b881895a9ed"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.4.3-linux-x64-cflinuxfs3-36aaa3d8.tgz"
    version = "7.4.3"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-11-30T00:00:00Z
    link = "http://php.net/supported-versions.php"
    match = "7.2.\\d+"
    name = "php"
    version_line = "7.2.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-12-06T00:00:00Z
    link = "http://php.net/supported-versions.php"
    match = "7.3.\\d+"
    name = "php"
    version_line = "7.3.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-11-08T00:00:00Z
    link = "http://php.net/supported-versions.php"
    match = "7.4.\\d+"
    name = "php"
    version_line = "7.4.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
